// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TotpAPI.Models.Context;

#nullable disable

namespace TotpAPI.Migrations
{
    [DbContext(typeof(UserVaultContext))]
    [Migration("20220531174238_NewIdeea")]
    partial class NewIdeea
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TotpAPI.Models.UserVault", b =>
                {
                    b.Property<int>("UserVaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserVaultId");

                    b.ToTable("UserVaults");
                });
#pragma warning restore 612, 618
        }
    }
}
